server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore.jks
    key-store-password: zaq1@WSX
    key-alias: easystepselfsigned
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: wardasek
    password: zawoja2044
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect